/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.telas;

import com.mycompany.ferramentas.Constantes;
import com.mycompany.ferramentas.DadosTemp;
import com.mycompany.ferramentas.Formularios;
import com.mycompany.modelo.DaoProdutos;
import com.mycompany.modelo.ModProdutos;
import javax.swing.JOptionPane;

/**
 *
 * @author sthefany.1921
 */
public class RegProdutos extends javax.swing.JFrame {

    /**
     * Creates new form Registrar
     */
    public RegProdutos() {
        initComponents();
        
        if(!existeDadosTemporarios()){
            DaoProdutos daoProdutos = new DaoProdutos();
            
            int id = daoProdutos.buscarProximoId();
            if(id >= 0)
                tfId.setText(String.valueOf(id));
            
            btnAcao.setText(Constantes.btn_salvar_text);
            btnExcluir.setVisible(false);
        }else{
            btnAcao.setText(Constantes.btn_alterar_text);
            btnExcluir.setVisible(true);
        }
        setLocationRelativeTo(null);
//        tfCodigo.setEditable(false);
        tfId.setEnabled(false);
    }
    private Boolean existeDadosTemporarios(){        
        if(DadosTemp.tempObject instanceof ModProdutos){
            int id = ((ModProdutos) DadosTemp.tempObject).getId();
            int codigo = ((ModProdutos) DadosTemp.tempObject).getCodigo();
            String nome = ((ModProdutos) DadosTemp.tempObject).getNome();
            Double preco = ((ModProdutos) DadosTemp.tempObject).getPreco();
            Double acrescimo = ((ModProdutos) DadosTemp.tempObject).getAcrescimo();
            Double novopreco = ((ModProdutos) DadosTemp.tempObject).getNovopreco();
            
            tfId.setText(String.valueOf(id));
            tfCodigo.setText(String.valueOf(codigo));
            tfNome.setText(nome);
            tfPreco.setText(String.valueOf(preco));
            tfAcrescimo.setText(String.valueOf(acrescimo));
            tfnovovalor.setText(String.valueOf(novopreco));
            
        
            DadosTemp.tempObject = null;
            
            return true;
        }else
            return false;
    }
    
    private void inserir(){
        DaoProdutos daoProdutos = new DaoProdutos();
        
        if (daoProdutos.inserir(Integer.parseInt(tfId.getText()), Integer.parseInt(tfCodigo.getText()), tfNome.getText(), Double.parseDouble(tfPreco.getText()), Double.parseDouble(tfAcrescimo.getText()), Double.parseDouble(tfnovovalor.getText()))){
            JOptionPane.showMessageDialog(null, "Produto salvo com sucesso!");
            tfId.setText(String.valueOf(daoProdutos.buscarProximoId()));
            tfCodigo.setText("");
            tfNome.setText("");
            tfPreco.setText("");
            tfAcrescimo.setText("");
            tfnovovalor.setText("");
        }else{
            JOptionPane.showMessageDialog(null, "Não foi possível salvar o produto!");
        }
    }
    
    private void alterar(){
        DaoProdutos daoProdutos = new DaoProdutos();
        
        if (daoProdutos.alterar(Integer.parseInt(tfId.getText()),Integer.parseInt(tfCodigo.getText()), tfNome.getText(), Double.parseDouble(tfPreco.getText()), Double.parseDouble(tfAcrescimo.getText()), Double.parseDouble(tfnovovalor.getText()))){
            JOptionPane.showMessageDialog(null, "Produto alterado com sucesso!");
            tfId.setText("");
            tfCodigo.setText("");
            tfNome.setText("");
            tfPreco.setText("");
            tfAcrescimo.setText("");
            tfnovovalor.setText("");
            
        }else{
            JOptionPane.showMessageDialog(null, "Não foi possível alterar o produto!");
        }
        
        ((ListProdutos) Formularios.listProdutos).listarTodos();
        
        dispose();
    }
    
    private void excluir(){
        DaoProdutos daoProdutos = new DaoProdutos();
        
        if (daoProdutos.excluir(Integer.parseInt(tfId.getText()))){
            JOptionPane.showMessageDialog(null, "Produto " + tfNome.getText() + " excluído com sucesso!");
            tfId.setText("");
            tfCodigo.setText("");
            tfNome.setText("");
            tfPreco.setText("");
            tfAcrescimo.setText("");
            tfnovovalor.setText("");
            
        }else{
            JOptionPane.showMessageDialog(null, "Não foi possível excluir o produto!");
        }
        
        ((ListProdutos) Formularios.listProdutos).listarTodos();
        
        dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tfNome = new javax.swing.JTextField();
        tfPreco = new javax.swing.JTextField();
        tfAcrescimo = new javax.swing.JTextField();
        btnExcluir = new javax.swing.JButton();
        btnAcao = new javax.swing.JButton();
        tfnovovalor = new javax.swing.JTextField();
        tfCodigo = new javax.swing.JTextField();
        tfId = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Registro");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 51));
        jLabel1.setText("Registrar novo produto");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 0, 51));
        jLabel2.setText("Código");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 0, 51));
        jLabel3.setText("Nome");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 0, 51));
        jLabel4.setText("Preço");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 0, 51));
        jLabel5.setText("Acréscimo (%)");

        tfAcrescimo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfAcrescimoFocusLost(evt);
            }
        });

        btnExcluir.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnExcluir.setForeground(new java.awt.Color(153, 0, 51));
        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnAcao.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnAcao.setForeground(new java.awt.Color(153, 0, 51));
        btnAcao.setText("Salvar");
        btnAcao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tfCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnAcao)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(tfNome, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(tfAcrescimo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfnovovalor, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(tfPreco))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnExcluir, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tfId, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29))))
            .addGroup(layout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(7, 7, 7)
                .addComponent(tfNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(7, 7, 7)
                .addComponent(tfPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfAcrescimo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfnovovalor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnExcluir)
                    .addComponent(btnAcao))
                .addGap(0, 13, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        int escolha = 
                JOptionPane.showConfirmDialog(
                        null, 
                        "Deseja realmente excluir o produto " + tfNome.getText() + "?");
        
        if(escolha == JOptionPane.YES_OPTION)
            excluir();
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnAcaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcaoActionPerformed
        if (btnAcao.getText() == Constantes.btn_salvar_text){
            inserir();
            
        }else if (btnAcao.getText() == Constantes.btn_alterar_text)
            alterar();
    }//GEN-LAST:event_btnAcaoActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        Formularios.regProdutos = null;
    }//GEN-LAST:event_formWindowClosed

    private void tfAcrescimoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfAcrescimoFocusLost
        Double preco = 0.0, acrescimo = 0.0, novoValor = 0.0;
        
        preco = Double.valueOf(tfPreco.getText().replace(",", "."));
        acrescimo = Double.valueOf(tfAcrescimo.getText().replace(",", "."));
        
        novoValor = (preco * acrescimo) + preco;
        
        tfnovovalor.setText(String.valueOf(novoValor));
    }//GEN-LAST:event_tfAcrescimoFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegProdutos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAcao;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField tfAcrescimo;
    private javax.swing.JTextField tfCodigo;
    private javax.swing.JTextField tfId;
    private javax.swing.JTextField tfNome;
    private javax.swing.JTextField tfPreco;
    private javax.swing.JTextField tfnovovalor;
    // End of variables declaration//GEN-END:variables
}
